---
- name: Control crafty
  become: false
  hosts: container_host
  gather_facts: false

  pre_tasks:
    - name: Start crafty container
      ansible.builtin.systemd_service:
        name: crafty
        scope: user
        state: started
      tags: start

  tasks:
    - name: Aquire API token
      ansible.builtin.import_tasks:
        tasks/authentication-and-token.yml
      delegate_to: localhost
      tags: always

    - name: Load server_ids
      ansible.builtin.import_tasks:
        tasks/list-servers.yml
      delegate_to: localhost
      tags: always

    - name: Start all servers
      ansible.builtin.import_tasks:
        tasks/start-all.yml
      delegate_to: localhost
      tags: start

    - name: Stop all servers
      ansible.builtin.import_tasks:
        tasks/stop-all.yml
      delegate_to: localhost
      tags: stop

  post_tasks:
    - name: Stop crafty container
      ansible.builtin.systemd_service:
        name: crafty
        scope: user
        state: stopped
      tags: stop

...
