---
- name: Initialize token if necessary
  ansible.builtin.include_tasks:
    init_token.yml
  when: crafty_token is undefined

- name: Get server list
  ansible.builtin.uri:
    url: "{{ crafty_api_base_url }}/servers"
    method: GET
    headers:
      Authorization: "{{ crafty_token }}"
    validate_certs: "{{ crafty_api_validate_certs }}"
  delegate_to: localhost
  register: results

- name: Save server_ids
  ansible.builtin.set_fact:
    crafty_server_ids: "{{ results | json_query('json.data[*].server_id') }}"

...
