vpn:
  vars:
    ansible_user: damien
    wireguard_endpoint: "192.168.50.82"
    wireguard_port: "51820"
    wireguard_network: "10.11.12.0/24"
  children:
    vpn_public:
      hosts:
        external:
          ansible_host: 192.168.50.82
          wireguard_address: 10.0.0.1/24
      vars:
        wireguard_forwards:
          - port: 8080
            protocol: tcp
            destination: 10.0.0.2:80
          - port: 8081
            protocol: tcp
            destination: 10.0.0.3:80
    vpn_private:
      hosts:
        internal1:
          ansible_host: 192.168.50.78
          wireguard_address: 10.0.0.2/24
        internal2:
          ansible_host: 192.168.50.101
          wireguard_address: 10.0.0.3/24
