---
- name: Crafty Server API Playground
  become: false
  hosts: container_host
  gather_facts: false

  vars:
    crafty_server_id: 1

  tasks:
    - name: Start
      ansible.builtin.include_role:
        name: crafty
        tasks_from: server_control.yml
      vars:
        crafty_server_running: true

    - name: Stop
      ansible.builtin.include_role:
        name: crafty
        tasks_from: server_control.yml
      vars:
        crafty_server_running: false

    - name: Debug
      ansible.builtin.debug:
        var: crafty_server_stats

    - name: Stop
      ansible.builtin.include_role:
        name: crafty
        tasks_from: server_control.yml
      vars:
        crafty_server_running: false

    - name: Start
      ansible.builtin.include_role:
        name: crafty
        tasks_from: server_control.yml
      vars:
        crafty_server_running: true

    - name: Debug
      ansible.builtin.debug:
        var: crafty_server_stats
